:Author: Jrork
:Email: 
:Date: 08/05/2019
:Revision: version#
:License: Public Domain

= Project: Gatsby_with_sign

Describe your project

== Step 1: Installation


For example:

1. Open this file
2. Edit as you like
3. Release to the World!

== Step 2: Assemble the circuit

Assemble the circuit following the diagram layout.png attached to the sketch

== Step 3: Load the code

Upload the code contained in this sketch on to your board

=== Folder structure

....
 sketch123                => Arduino sketch folder
  ├── sketch123.ino       => main Arduino file
  ├── schematics.png      => (optional) an image of the required schematics
  ├── layout.png          => (optional) an image of the layout
  └── ReadMe.adoc         => this file
....

=== License
This project is released under a {License} License.

=== Contributing
To contribute to this project please contact Jrork https://id.arduino.cc/Jrork

=== BOM
Add the bill of the materials you need for this project.

Arduino Uno R3 Development Board, Kit Microcontroller Based on ATmega328 and ATMEGA16U2 with USB Cable for Arduino, Original
https://smile.amazon.com/Development-Microcontroller-ATmega328-ATMEGA16U2-Original/dp/B07MMMSNYH/ref=sr_1_6?keywords=Arduino+uno&qid=1560098669&s=electronics&sr=1-6

Aclorol WS2811 Addressable LED Strip 5050 RGB 5m 300LEDs Flexible Rope Light Dream Color Non-Waterproof Black PCBDC 12V. https://smile.amazon.com/gp/product/B07FVYR84H/ref=ppx_yo_dt_b_asin_title_o04_s00?ie=UTF8&psc=1

eTopxizu 12v 30a Dc Universal Regulated Switching Power Supply 360w https://smile.amazon.com/gp/product/B00D7CWSCG/ref=ppx_yo_dt_b_asin_title_o05_s01?ie=UTF8&psc=1

CTOO JST SM 3 Pin Connector LED Power Male to Female SM Wire Cable Adapter for WS2812B WS2812 WS2811 LED Light Strip 10 Pair
https://smile.amazon.com/gp/product/B07GGPQXFC/ref=ppx_yo_dt_b_asin_title_o06_s00?ie=UTF8&psc=1

Metallor Alpha Pots Linear B250k Tone Potentiometer Electronics for Electric Guitar or Bass.(Larger B250k). https://smile.amazon.com/gp/product/B07KXF9RNP/ref=ppx_yo_dt_b_asin_title_o02_s00?ie=UTF8&psc=1

YETAIDA 4 Pack Universial 4x4 Matrix Array Keyboard 16 Key Membrane Switch Keypad for Arduino https://smile.amazon.com/gp/product/B07Q7FW8B9/ref=ppx_yo_dt_b_asin_title_o03_s00?ie=UTF8&psc=1

RGBSIGHT 40FT 18 Gauge RGBW LED Strip Extension Cable 18AWG 5pin 5 Color Stand Wire for RGBW RGBWW LED Ribbon Lamp Tape Lighting (40 Feet per Spool) https://smile.amazon.com/gp/product/B0154H7BLE/ref=ppx_yo_dt_b_asin_title_o09_s00?ie=UTF8&psc=1

=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents.
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
